name: Build Application

on: [push]

jobs:
  build:
<<<<<<< HEAD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Define version number
        id: vars
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - name: Create Executable
        run: pyinstaller --onefile --noconsole --name=ServerEditor.${{ steps.vars.outputs.version }} main.py
      - name: Upload Executable as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: server-editor
          path: dist/ServerEditor.${{ steps.vars.outputs.version }}
=======
    runs-on: windows-latest
>>>>>>> parent of 0221632 (ServerEditor V1.0)

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller  # Add any other necessary packages

    - name: Build Executable
      run: pyinstaller --onefile --noconsole --name=ServerEditor main.py

    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: ServerEditor
        path: dist/ServerEditor.exe