name: Build Application

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller  # Add any other necessary packages

    - name: Build Executable
      run: pyinstaller --onefile --name=ServerEditor main.py

    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: ServerEditor
        path: dist/main.exe